import fs from 'node:fs/promises'
import { afterEach, describe, expect, it, onTestFinished, vi } from 'vitest'
import { buildChangelog, formatChangelog } from '../scripts/build-changelog.ts'
import makeTempDir from './helpers/makeTempDir.ts'
import removeDir from './helpers/removeDir.ts'

const ORIGINAL_CWD = process.cwd()
const ORIGINAL_ENV = { ...process.env }

const INTRO =
  'This file is automatically generated from the [GitHub releases page](https://github.com/raineorshine/npm-check-updates/releases). Do not edit manually.'
const PREFIX = `# Changelog\n\n${INTRO}\n\n`

/** Switches to an empty working directory that the generated CHANGELOG.md is written to. */
const chdirTemp = async (): Promise<void> => {
  const tempDir = await makeTempDir('ncu-build-changelog-')
  // chdir back before removing, otherwise the cwd is still inside the directory being deleted
  onTestFinished(async () => {
    process.chdir(ORIGINAL_CWD)
    await removeDir(tempDir)
  })
  process.chdir(tempDir)
}

/** Stubs the GitHub API with a single page of releases. */
const stubReleases = (releases: unknown[]) => {
  const fetchMock = vi.fn(async (_input: string | URL) => new Response(JSON.stringify(releases), { status: 200 }))
  vi.stubGlobal('fetch', fetchMock)
  return fetchMock
}

afterEach(async () => {
  process.env = { ...ORIGINAL_ENV }
  vi.restoreAllMocks()
  vi.unstubAllGlobals()
})

describe('build-changelog', () => {
  it('renders published releases newest first', async () => {
    await chdirTemp()

    stubReleases([
      { tag_name: 'v1.0.0', body: 'old release body', draft: false, published_at: '2024-01-01T00:00:00.000Z' },
      { tag_name: 'v3.0.0', body: 'draft body', draft: true, published_at: null },
      { tag_name: 'v2.0.0', body: null, draft: false, published_at: '2024-02-01T12:00:00.000Z' },
    ])

    await buildChangelog()

    expect(await fs.readFile('CHANGELOG.md', 'utf8')).toBe(
      `${PREFIX}## [2.0.0] - 2024-02-01\n\n## [1.0.0] - 2024-01-01\n\nold release body\n`,
    )
  })

  it('rebuilds from every release, even when a single release triggered the run', async () => {
    await chdirTemp()

    // a release whose run was replaced while pending is missing from the existing file, so the release that triggered
    // this run cannot simply be prepended
    await fs.writeFile('CHANGELOG.md', `${PREFIX}## [1.0.0] - 2024-01-01\n\nold release body\n`)

    process.env.GITHUB_EVENT_NAME = 'release'
    process.env.GITHUB_EVENT_ACTION = 'published'
    process.env.RELEASE_TAG = 'v3.0.0'

    const fetchMock = stubReleases([
      { tag_name: 'v3.0.0', body: 'newest release', draft: false, published_at: '2024-03-01T00:00:00.000Z' },
      { tag_name: 'v2.0.0', body: 'skipped release', draft: false, published_at: '2024-02-01T00:00:00.000Z' },
      { tag_name: 'v1.0.0', body: 'old release body', draft: false, published_at: '2024-01-01T00:00:00.000Z' },
    ])

    await buildChangelog()

    expect(await fs.readFile('CHANGELOG.md', 'utf8')).toBe(
      `${PREFIX}## [3.0.0] - 2024-03-01\n\nnewest release\n\n## [2.0.0] - 2024-02-01\n\nskipped release\n\n## [1.0.0] - 2024-01-01\n\nold release body\n`,
    )
    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(String(fetchMock.mock.calls[0][0])).toContain('/releases?per_page=100&page=1')
  })

  it('nests release body headings and formats them for prettier and markdownlint', async () => {
    await chdirTemp()

    // a hand-written release body: headings that would collide with the version heading, and lists that neither
    // prettier nor markdownlint would accept as-is
    const body = ['# What’s Changed', '* a fix   ', '### Details', '#### Deeper', '```js', 'ncu()', '```'].join('\n')

    stubReleases([{ tag_name: 'v1.0.0', body, draft: false, published_at: '2024-01-01T00:00:00.000Z' }])

    await buildChangelog()

    expect(await fs.readFile('CHANGELOG.md', 'utf8')).toBe(
      `${PREFIX}## [1.0.0] - 2024-01-01\n\n### What’s Changed\n\n- a fix\n\n#### Details\n\n##### Deeper\n\n\`\`\`js\nncu()\n\`\`\`\n`,
    )
  })

  it('leaves comments inside fenced code blocks alone', async () => {
    await chdirTemp()

    const fenced = ['```bash', '# install dependencies', 'npm i', '```']
    const tildeFenced = ['~~~sh', '## not a heading', '~~~']
    const body = ['## Usage', '', ...fenced, '', ...tildeFenced].join('\n')

    stubReleases([{ tag_name: 'v1.0.0', body, draft: false, published_at: '2024-01-01T00:00:00.000Z' }])

    await buildChangelog()

    expect(await fs.readFile('CHANGELOG.md', 'utf8')).toBe(
      `${PREFIX}## [1.0.0] - 2024-01-01\n\n### Usage\n\n\`\`\`bash\n# install dependencies\nnpm i\n\`\`\`\n\n\`\`\`sh\n## not a heading\n\`\`\`\n`,
    )
  })

  it('disables rules that markdownlint cannot fix, without duplicating the comment on the next build', async () => {
    // a code fence with no language violates MD040, which has no automatic fix
    const changelog = `${PREFIX}## [1.0.0] - 2024-01-01\n\n\`\`\`\nncu\n\`\`\`\n`

    const disabled = await formatChangelog(changelog)
    expect(disabled).toBe(
      `${PREFIX}<!-- markdownlint-disable MD040 -->\n\n## [1.0.0] - 2024-01-01\n\n\`\`\`\nncu\n\`\`\`\n`,
    )

    // rebuilding an already generated changelog is a no-op
    expect(await formatChangelog(disabled)).toBe(disabled)
  })
})
