import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { buildChangelog } from '../scripts/build-changelog.ts'

const ORIGINAL_CWD = process.cwd()
const ORIGINAL_ENV = { ...process.env }

const INTRO =
  'This file is automatically generated from the [GitHub releases page](https://github.com/raineorshine/npm-check-updates/releases). Do not edit manually.'
const PREFIX = `# Changelog\n\n${INTRO}\n\n`

afterEach(async () => {
  process.chdir(ORIGINAL_CWD)
  process.env = { ...ORIGINAL_ENV }
  vi.restoreAllMocks()
  vi.unstubAllGlobals()
})

describe('build-changelog', () => {
  it('prepends only the published release on the fast path', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ncu-build-changelog-'))
    process.chdir(dir)

    const existing = `${PREFIX}## [1.0.0] - 2024-01-01\n\nold release body\n`
    await fs.writeFile('CHANGELOG.md', existing)

    process.env.GITHUB_EVENT_NAME = 'release'
    process.env.GITHUB_EVENT_ACTION = 'published'
    process.env.RELEASE_TAG = 'v2.0.0'

    const fetchMock = vi.fn(async (input: string | URL) => {
      const url = String(input)
      if (url.endsWith('/releases/tags/v2.0.0')) {
        return new Response(
          JSON.stringify({
            tag_name: 'v2.0.0',
            body: 'new release body',
            draft: false,
            published_at: '2024-02-01T12:00:00.000Z',
          }),
          { status: 200 },
        )
      }
      throw new Error(`Unexpected fetch URL: ${url}`)
    })

    vi.stubGlobal('fetch', fetchMock)

    await buildChangelog()

    const changelog = await fs.readFile('CHANGELOG.md', 'utf8')
    expect(changelog).toBe(
      `${PREFIX}## [2.0.0] - 2024-02-01\n\nnew release body\n\n## [1.0.0] - 2024-01-01\n\nold release body\n`,
    )
    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(String(fetchMock.mock.calls[0][0])).toContain('/releases/tags/v2.0.0')
  })

  it('falls back to the full rebuild when the published release is not newer', async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ncu-build-changelog-'))
    process.chdir(dir)

    await fs.writeFile('CHANGELOG.md', `${PREFIX}## [1.0.0] - 2024-03-01\n\nexisting release\n`)

    process.env.GITHUB_EVENT_NAME = 'release'
    process.env.GITHUB_EVENT_ACTION = 'published'
    process.env.RELEASE_TAG = 'v2.0.0'

    const fetchMock = vi.fn(async (input: string | URL) => {
      const url = String(input)
      if (url.endsWith('/releases/tags/v2.0.0')) {
        return new Response(
          JSON.stringify({
            tag_name: 'v2.0.0',
            body: null,
            draft: false,
            published_at: '2024-02-01T12:00:00.000Z',
          }),
          { status: 200 },
        )
      }
      if (url.includes('/releases?per_page=100&page=1')) {
        return new Response(
          JSON.stringify([
            {
              tag_name: 'v1.0.0',
              body: 'existing release',
              draft: false,
              published_at: '2024-03-01T00:00:00.000Z',
            },
            {
              tag_name: 'v2.0.0',
              body: null,
              draft: false,
              published_at: '2024-02-01T12:00:00.000Z',
            },
          ]),
          { status: 200 },
        )
      }
      throw new Error(`Unexpected fetch URL: ${url}`)
    })

    vi.stubGlobal('fetch', fetchMock)

    await buildChangelog()

    const changelog = await fs.readFile('CHANGELOG.md', 'utf8')
    expect(changelog).toBe(`${PREFIX}## [1.0.0] - 2024-03-01\n\nexisting release\n\n## [2.0.0] - 2024-02-01\n`)
    expect(fetchMock.mock.calls.some(([input]) => String(input).includes('/releases?per_page=100&page=1'))).toBe(true)
  })
})
