import fs from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

/** A GitHub release as returned by the GitHub REST API. */
interface Release {
  tag_name: string
  body: string | null
  draft: boolean
  published_at: string | null
}

type PublishedRelease = Release & { published_at: string }

const REPO = process.env.GITHUB_REPOSITORY || 'raineorshine/npm-check-updates'

const INTRO = `This file is automatically generated from the [GitHub releases page](https://github.com/${REPO}/releases). Do not edit manually.`

const HEADER_PREFIX = `# Changelog\n\n${INTRO}\n\n`

/** Narrows a release to one that is published and has a non-null published_at value. */
const isPublished = (release: Release): release is PublishedRelease => !release.draft && release.published_at !== null

/** Builds GitHub API headers, including auth when available. */
const getHeaders = (): Record<string, string> => {
  const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN
  const authHeader = token ? { authorization: ['Bearer', token].join(' ') } : null
  return {
    accept: 'application/vnd.github+json',
    ...(authHeader ?? {}),
  }
}

/** Fetches every release from the GitHub API, following pagination. */
const fetchReleases = async (): Promise<Release[]> => {
  const releases: Release[] = []

  for (let page = 1; ; page++) {
    const res = await fetch(`https://api.github.com/repos/${REPO}/releases?per_page=100&page=${page}`, {
      headers: getHeaders(),
    })

    if (!res.ok) {
      throw new Error(`GitHub API request failed: ${res.status} ${res.statusText}`)
    }

    const batch = (await res.json()) as Release[]
    releases.push(...batch)

    if (batch.length < 100) break
  }

  return releases
}

/** Fetches a single release by tag from the GitHub API. */
const fetchReleaseByTag = async (tag: string): Promise<Release> => {
  const res = await fetch(`https://api.github.com/repos/${REPO}/releases/tags/${encodeURIComponent(tag)}`, {
    headers: getHeaders(),
  })

  if (!res.ok) {
    throw new Error(`GitHub API request failed: ${res.status} ${res.statusText}`)
  }

  return (await res.json()) as Release
}

/** Shifts markdown headings down two levels so that release bodies nest under their version heading. */
const shiftHeadings = (body: string): string =>
  body.replace(/\r\n/g, '\n').replace(/^(#{1,6})(?=\s)/gm, hashes => '#'.repeat(Math.min(hashes.length + 2, 6)))

/** Renders a single release as a markdown section. */
const renderRelease = (release: PublishedRelease): string => {
  const version = release.tag_name.replace(/^v/, '')
  const date = release.published_at.slice(0, 10)
  const body = shiftHeadings((release.body ?? '').trim())
  return body ? `## [${version}] - ${date}\n\n${body}` : `## [${version}] - ${date}`
}

/** Generates the full contents of CHANGELOG.md from the repo's GitHub releases, newest first. */
export async function renderChangelog(): Promise<string> {
  const allReleases = await fetchReleases()

  const sections = allReleases
    .filter(isPublished)
    .sort((a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime())
    .map(renderRelease)

  return `# Changelog\n\n${INTRO}${sections.length > 0 ? `\n\n${sections.join('\n\n')}` : ''}\n`
}

/** Extracts the date from the first release section heading in CHANGELOG.md. */
const extractFirstSectionDate = (changelog: string): string | null => {
  const match = changelog.match(/^## \[[^\]]+\] - (\d{4}-\d{2}-\d{2})$/m)
  return match ? match[1] : null
}

/** Attempts to generate a one-release prepend for the common release:published event. */
const tryRenderFastPath = async (): Promise<string | null> => {
  if (process.env.GITHUB_EVENT_NAME !== 'release' || process.env.GITHUB_EVENT_ACTION !== 'published') {
    return null
  }

  const releaseTag = process.env.RELEASE_TAG
  if (!releaseTag) {
    return null
  }

  let existing: string
  try {
    existing = await fs.readFile('CHANGELOG.md', 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null
    }
    throw error
  }

  if (!existing.startsWith(HEADER_PREFIX)) {
    return null
  }

  const version = releaseTag.replace(/^v/, '')
  if (existing.includes(`## [${version}] - `)) {
    return null
  }

  const firstSectionDate = extractFirstSectionDate(existing)
  if (!firstSectionDate) {
    return null
  }

  const release = await fetchReleaseByTag(releaseTag)
  if (!isPublished(release)) {
    return null
  }

  if (new Date(release.published_at).getTime() <= new Date(`${firstSectionDate}T00:00:00.000Z`).getTime()) {
    return null
  }

  const existingSections = existing.slice(HEADER_PREFIX.length)
  return `${HEADER_PREFIX}${renderRelease(release)}\n\n${existingSections}`
}

/** Generates and writes CHANGELOG.md. */
export async function buildChangelog(): Promise<void> {
  const fastPathChangelog = await tryRenderFastPath()

  if (fastPathChangelog !== null) {
    console.log(`[build-changelog] Fast path: prepending ${process.env.RELEASE_TAG}`)
    await fs.writeFile('CHANGELOG.md', fastPathChangelog)
    console.log('[build-changelog] Wrote CHANGELOG.md')
    return
  }

  console.log('[build-changelog] Full rebuild: fetching all releases...')
  const changelog = await renderChangelog()
  await fs.writeFile('CHANGELOG.md', changelog)
  console.log('[build-changelog] Wrote CHANGELOG.md')
}

const isDirectRun = import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href

if (isDirectRun) {
  buildChangelog().catch(err => {
    console.error(err?.stack || err)
    process.exit(1)
  })
}
