import fs from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

/** A GitHub release as returned by the GitHub REST API. */
interface Release {
  tag_name: string
  body: string | null
  draft: boolean
  published_at: string | null
}

const REPO = process.env.GITHUB_REPOSITORY || 'raineorshine/npm-check-updates'

const INTRO = `This file is automatically generated from the [GitHub releases page](https://github.com/${REPO}/releases). Do not edit manually.`

/** Fetches every release from the GitHub API, following pagination. */
const fetchReleases = async (): Promise<Release[]> => {
  const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN
  const releases: Release[] = []

  for (let page = 1; ; page++) {
    const res = await fetch(`https://api.github.com/repos/${REPO}/releases?per_page=100&page=${page}`, {
      headers: {
        accept: 'application/vnd.github+json',
        ...(token ? { authorization: `Bearer ${token}` } : null),
      },
    })

    if (!res.ok) {
      throw new Error(`GitHub API request failed: ${res.status} ${res.statusText}`)
    }

    const batch = (await res.json()) as Release[]
    releases.push(...batch)

    if (batch.length < 100) break
  }

  return releases
}

/** Shifts markdown headings down two levels so that release bodies nest under their version heading. */
const shiftHeadings = (body: string): string =>
  body.replace(/\r\n/g, '\n').replace(/^(#{1,6})(?=\s)/gm, hashes => '#'.repeat(Math.min(hashes.length + 2, 6)))

/** Renders a single release as a markdown section. */
const renderRelease = (release: Release): string => {
  const version = release.tag_name.replace(/^v/, '')
  const date = release.published_at!.slice(0, 10)
  const body = shiftHeadings((release.body ?? '').trim())
  return body ? `## [${version}] - ${date}\n\n${body}` : `## [${version}] - ${date}`
}

/** Generates the full contents of CHANGELOG.md from the repo's GitHub releases, newest first. */
export async function renderChangelog(): Promise<string> {
  const allReleases = await fetchReleases()

  const sections = allReleases
    .filter(release => !release.draft && release.published_at)
    .sort((a, b) => new Date(b.published_at!).getTime() - new Date(a.published_at!).getTime())
    .map(renderRelease)

  return `# Changelog\n\n${INTRO}${sections.length > 0 ? `\n\n${sections.join('\n\n')}` : ''}\n`
}

/** Generates and writes CHANGELOG.md. */
export async function buildChangelog(): Promise<void> {
  console.log('[build-changelog] Fetching releases...')
  const changelog = await renderChangelog()
  await fs.writeFile('CHANGELOG.md', changelog)
  console.log('[build-changelog] Wrote CHANGELOG.md')
}

const isDirectRun = import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href

if (isDirectRun) {
  buildChangelog().catch(err => {
    console.error(err?.stack || err)
    process.exit(1)
  })
}
