import fs from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { parse as parseJsonc } from 'jsonc-parser'
import { applyFixes } from 'markdownlint'
import { lint, readConfig } from 'markdownlint/promise'
import prettier from 'prettier'

/** A GitHub release as returned by the GitHub REST API. */
interface Release {
  tag_name: string
  body: string | null
  draft: boolean
  published_at: string | null
}

type PublishedRelease = Release & { published_at: string }

const REPO = process.env.GITHUB_REPOSITORY || 'raineorshine/npm-check-updates'

const INTRO = `This file is automatically generated from the [GitHub releases page](https://github.com/${REPO}/releases). Do not edit manually.`

const HEADER_PREFIX = `# Changelog\n\n${INTRO}\n\n`

/** Repo root, so that the changelog is formatted with the same config that CI lints it with, no matter the cwd. */
const ROOT = path.join(import.meta.dirname, '..')

/** Matches the generated markdownlint disable comment, which is regenerated on every build. */
const DISABLE_COMMENT_RE = /^<!-- markdownlint-disable [^>]*-->\n\n/m

/** Upper bound on markdownlint fix passes. Two or three are enough in practice; the limit only guards against a fix that oscillates. */
const MAX_FIX_PASSES = 10

/** Narrows a release to one that is published and has a non-null published_at value. */
const isPublished = (release: Release): release is PublishedRelease => !release.draft && release.published_at !== null

/** Builds GitHub API headers, including auth when available. */
const getHeaders = (): Record<string, string> => {
  const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN
  const authHeader = token ? { authorization: ['Bearer', token].join(' ') } : null
  return {
    accept: 'application/vnd.github+json',
    ...authHeader,
  }
}

/** Fetches every release from the GitHub API, following pagination. */
const fetchReleases = async (): Promise<Release[]> => {
  const releases: Release[] = []

  for (let page = 1; ; page++) {
    const res = await fetch(`https://api.github.com/repos/${REPO}/releases?per_page=100&page=${page}`, {
      headers: getHeaders(),
    })

    if (!res.ok) {
      throw new Error(`GitHub API request failed: ${res.status} ${res.statusText}`)
    }

    const batch = (await res.json()) as Release[]
    releases.push(...batch)

    if (batch.length < 100) break
  }

  return releases
}

/** Matches an atx heading. Indented code blocks are excluded for free, as they are indented by at least four spaces. */
const HEADING_RE = /^(#{1,6})(?=\s)/

/** Matches the start or end of a fenced code block. */
const FENCE_RE = /^ {0,3}(`{3,}|~{3,})/

/**
 * Splits a release body into lines, marking which lines are headings. Lines inside a fenced code block are never
 * headings, otherwise a shell snippet like `# install dependencies` would be rewritten as one.
 */
const parseLines = (body: string): { text: string; level: number }[] => {
  let fence: string | null = null

  return body.split('\n').map(text => {
    const fenceMatch = text.match(FENCE_RE)

    if (fence) {
      // a fence is closed by a run of the same character that is at least as long, with nothing after it
      if (
        fenceMatch?.[1].startsWith(fence[0]) &&
        fenceMatch[1].length >= fence.length &&
        !text.slice(fenceMatch[0].length).trim()
      ) {
        fence = null
      }
      return { text, level: 0 }
    }

    if (fenceMatch) {
      fence = fenceMatch[1]
      return { text, level: 0 }
    }

    return { text, level: text.match(HEADING_RE)?.[1].length ?? 0 }
  })
}

/**
 * Shifts markdown headings down so that release bodies nest under their version heading. The shallowest heading in the
 * body becomes an h3, and each heading is capped at one level deeper than the one before it, otherwise the result trips
 * markdownlint's heading-increment rule, which has no automatic fix.
 */
const shiftHeadings = (body: string): string => {
  const lines = parseLines(body.replaceAll('\r\n', '\n'))
  const levels = lines.filter(line => line.level > 0).map(line => line.level)
  if (levels.length === 0) return lines.map(line => line.text).join('\n')

  const shift = 3 - Math.min(...levels)
  // the version heading is an h2, so the first body heading may be at most an h3
  let previous = 2

  return lines
    .map(line => {
      if (line.level === 0) return line.text
      const level = Math.min(Math.max(line.level + shift, 3), previous + 1, 6)
      previous = level
      return line.text.replace(HEADING_RE, '#'.repeat(level))
    })
    .join('\n')
}

/** Renders a single release as a markdown section. */
const renderRelease = (release: PublishedRelease): string => {
  const version = release.tag_name.replace(/^v/, '')
  const date = release.published_at.slice(0, 10)
  const body = shiftHeadings((release.body ?? '').trim())
  return body ? `## [${version}] - ${date}\n\n${body}` : `## [${version}] - ${date}`
}

/** Generates the full contents of CHANGELOG.md from the repo's GitHub releases, newest first. */
export async function renderChangelog(): Promise<string> {
  const allReleases = await fetchReleases()

  const sections = allReleases
    .filter(isPublished)
    .sort((a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime())
    .map(renderRelease)

  return `# Changelog\n\n${INTRO}${sections.length > 0 ? `\n\n${sections.join('\n\n')}` : ''}\n`
}

/** Disables the given rules for the whole file by inserting an inline comment below the intro. */
const disableRules = (content: string, rules: string[]): string =>
  content.replace(HEADER_PREFIX, `${HEADER_PREFIX}<!-- markdownlint-disable ${rules.join(' ')} -->\n\n`)

/**
 * Formats the changelog the same way CI verifies it: prettier, then markdownlint --fix. Release bodies are authored by
 * hand on the GitHub releases page, so they routinely violate the repo's markdown rules. Anything that has no automatic
 * fix (a code fence without a language, for example) is disabled inline instead, so that a hand-written release body can
 * never break `npm run lint` on main.
 */
export async function formatChangelog(content: string): Promise<string> {
  // plugins are omitted since they are resolved relative to the cwd and only affect the typescript parser
  const { plugins: _plugins, ...prettierConfig } = (await prettier.resolveConfig(path.join(ROOT, 'CHANGELOG.md'))) ?? {}
  const prettierOptions: prettier.Options = { ...prettierConfig, parser: 'markdown' }
  const config = await readConfig(path.join(ROOT, '.markdownlint.json'), [
    text => parseJsonc(text) as Record<string, unknown>,
  ])

  // drop the previous disable comment so that the rules are recalculated from the current content
  let formatted = content.replace(DISABLE_COMMENT_RE, '')

  // a fix can reveal further errors, so fix until only unfixable errors are left
  for (let pass = 0; pass < MAX_FIX_PASSES; pass++) {
    formatted = await prettier.format(formatted, prettierOptions)
    const errors = (await lint({ strings: { changelog: formatted }, config })).changelog

    if (errors.every(error => !error.fixInfo)) {
      const unfixable = [...new Set(errors.map(error => error.ruleNames[0]))].sort()
      if (unfixable.length === 0) return formatted
      console.log(`[build-changelog] Disabling rules with no automatic fix: ${unfixable.join(', ')}`)
      return disableRules(formatted, unfixable)
    }

    formatted = applyFixes(formatted, errors)
  }

  throw new Error(`markdownlint fixes did not converge after ${MAX_FIX_PASSES} passes`)
}

/**
 * Generates and writes CHANGELOG.md.
 *
 * Every run rebuilds the file from the complete list of releases. Prepending only the release that triggered the run
 * would be unsafe: concurrency replaces a pending run when a newer one is queued, so a release whose run was dropped
 * would never make it into the changelog. A rebuild is a single request until the repo has more than 100 releases, so
 * there is nothing to gain from the shortcut either.
 */
export async function buildChangelog(): Promise<void> {
  console.log('[build-changelog] Fetching all releases...')
  const changelog = await renderChangelog()
  await fs.writeFile('CHANGELOG.md', await formatChangelog(changelog))
  console.log('[build-changelog] Wrote CHANGELOG.md')
}

const isDirectRun = import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href

if (isDirectRun) {
  try {
    await buildChangelog()
  } catch (err: any) {
    console.error(err?.stack || err)
    process.exit(1)
  }
}
