name: Lint & TypeCheck

on:
  push:
    branches:
      - main
      - '!dependabot/**'
  pull_request:
    branches:
      - '**'

env:
  FORCE_COLOR: 2
  NODE: 24

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name != 'pull_request' || github.event.pull_request.changed_files > 0

    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE }}
          cache: npm

      - name: Cache tsbuildinfo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: node_modules/.cache
          key: tsbuildinfo-${{ runner.os }}-${{ hashFiles('**/tsconfig.json') }}
          restore-keys: tsbuildinfo-${{ runner.os }}-

      - name: Install npm dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run typecheck
