name: zizmor

on:
  push:
    branches:
      - main
      - '!dependabot/**'
    paths:
      - '.github/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/**'
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name != 'pull_request' || github.event.pull_request.changed_files > 0

    permissions:
      security-events: write # upload SARIF to code scanning
      contents: read
      actions: read

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
